apiVersion: v1alpha1
kind: KubeletConfig
extraArgs:
  rotate-server-certificates: "true"
config:
  maxPods: 250
  shutdownGracePeriod: 15s
  shutdownGracePeriodCriticalPods: 10s
  imageGCHighThresholdPercent: 50
  imageGCLowThresholdPercent: 30
  imageMinimumGCAge: "30m"
##==========Example KubeletConfig for Talos 1.14 and later==========
# apiVersion: v1alpha1
# kind: KubeletConfig
# config:
#   crashLoopBackOff:
#     maxContainerRestartPeriod: 60s
#   imageMaximumGCAge: 168h
#   maxParallelImagePulls: 3
#   serializeImagePulls: false
#   shutdownGracePeriod: 90s
#   shutdownGracePeriodCriticalPods: 60s


