apiVersion: v1alpha1
kind: TimeSyncConfig
enabled: true
ntp:
  servers:
    - time.cloudflare.com
---
apiVersion: v1alpha1
kind: SysctlConfig
params:
  fs.inotify.max_queued_events: "65536"
  fs.inotify.max_user_instances: "8192"
  fs.inotify.max_user_watches: "524288"
  net.core.rmem_max: "7500000"
  net.core.wmem_max: "7500000"
  user.max_user_namespaces: "11255"
  net.core.default_qdisc: fq
  net.ipv4.tcp_congestion_control: bbr
  net.ipv4.tcp_fastopen: "3"
  net.ipv4.tcp_mtu_probing: "1"
  net.ipv4.tcp_rmem: 4096 87380 33554432
  net.ipv4.tcp_wmem: 4096 65536 33554432
  net.ipv4.tcp_window_scaling: "1"
  vm.nr_hugepages: "1024"
---
apiVersion: v1alpha1
kind: RegistryMirrorConfig
name: docker.io
endpoints:
  - url: https://mirror.gcr.io
  - url: https://registry-1.docker.io
  - url: https://docker.io
---
apiVersion: v1alpha1
kind: RegistryMirrorConfig
name: registry-1.docker.io
endpoints:
  - url: https://mirror.gcr.io
  - url: https://registry-1.docker.io
---
apiVersion: v1alpha1
kind: RegistryMirrorConfig
name: tccr.io
endpoints:
  - url: https://oci.trueforge.org
---
apiVersion: v1alpha1
kind: RegistryMirrorConfig
name: oci.trueforge.org
endpoints:
  - url: https://quay.io
  - url: https://oci.trueforge.org
---
apiVersion: v1alpha1
kind: RegistryMirrorConfig
name: cgr.dev
endpoints:
  - url: https://cgr.dev
---
apiVersion: v1alpha1
kind: RegistryMirrorConfig
name: factory.talos.dev
endpoints:
  - url: https://factory.talos.dev
---
apiVersion: v1alpha1
kind: RegistryMirrorConfig
name: gcr.io
endpoints:
  - url: https://gcr.io
---
apiVersion: v1alpha1
kind: RegistryMirrorConfig
name: ghcr.io
endpoints:
  - url: https://ghcr.io
---
apiVersion: v1alpha1
kind: RegistryMirrorConfig
name: k8s.gcr.io
endpoints:
  - url: https://k8s.gcr.io
---
apiVersion: v1alpha1
kind: RegistryMirrorConfig
name: mcr.microsoft.com
endpoints:
  - url: https://mcr.microsoft.com
---
apiVersion: v1alpha1
kind: RegistryMirrorConfig
name: public.ecr.aws
endpoints:
  - url: https://public.ecr.aws
---
apiVersion: v1alpha1
kind: RegistryMirrorConfig
name: quay.io
endpoints:
  - url: https://quay.io
---
apiVersion: v1alpha1
kind: RegistryMirrorConfig
name: registry.k8s.io
endpoints:
  - url: https://registry.k8s.io
