apiVersion: v1alpha1
kind: UnattendedInstallConfig
installer:
  image: factory.talos.dev/metal-installer/82866c01b2842b490c27a6f1a4996aae05f096c83db40ecda166b03da9deae46:v1.14.0
provisioning:
  diskSelector:
    match: disk.size <= 1600000000000u
  wipe: false
