apiVersion: v1alpha1
kind: KubeNodeConfig
taints:
  node-role.kubernetes.io/control-plane:
    $patch: delete
---
apiVersion: v1alpha1
kind: KubeletConfig
image: ghcr.io/siderolabs/kubelet:v1.37.0
extraArgs:
  rotate-server-certificates: "true"
config:
  maxPods: 250
  maxParallelImagePulls: 3
  serializeImagePulls: false
  shutdownGracePeriod: 15s
  shutdownGracePeriodCriticalPods: 10s
