apiVersion: v1alpha1
kind: KubeNodeConfig
taints:
  node-role.kubernetes.io/control-plane:
    $patch: delete
---
apiVersion: v1alpha1
kind: KubeletConfig
$patch: delete
---
machine:
  kubelet:
    extraArgs:
      rotate-server-certificates: "true"
    extraConfig:
      maxPods: 250
      maxParallelImagePulls: 3
      serializeImagePulls: false
      shutdownGracePeriod: 15s
      shutdownGracePeriodCriticalPods: 10s
    extraMounts:
      - destination: /var/openebs/local
        type: bind
        source: /var/openebs/local
        options: [bind, rshared, rw]
      - destination: /var/lib/longhorn
        type: bind
        source: /var/lib/longhorn
        options: [bind, rshared, rw]
