apiVersion: v1alpha1
kind: KubeTalosAPIAccessConfig
allowedRoles:
  - os:admin
allowedKubernetesNamespaces:
  - system-upgrade
---
apiVersion: v1alpha1
kind: KubeAPIServerConfig
image: registry.k8s.io/kube-apiserver:v1.37.0
certExtraSANs:
  - 127.0.0.1
  - ${VIP}
extraArgs:
  enable-aggregator-routing: "true"
---
apiVersion: v1alpha1
kind: KubeControllerManagerConfig
image: registry.k8s.io/kube-controller-manager:v1.37.0
extraArgs:
  bind-address: 0.0.0.0
---
apiVersion: v1alpha1
kind: KubeSchedulerConfig
image: registry.k8s.io/kube-scheduler:v1.37.0
extraArgs:
  bind-address: 0.0.0.0
config:
  apiVersion: kubescheduler.config.k8s.io/v1
  kind: KubeSchedulerConfiguration
  profiles:
    - pluginConfig:
        - args:
            defaultConstraints:
              - maxSkew: 1
                topologyKey: kubernetes.io/hostname
                whenUnsatisfiable: ScheduleAnyway
            defaultingType: List
          name: PodTopologySpread
      plugins:
        score:
          disabled:
            - name: ImageLocality
      schedulerName: default-scheduler
---
apiVersion: v1alpha1
kind: KubeProxyConfig
image: registry.k8s.io/kube-proxy:v1.37.0
enabled: false
config:
  metricsBindAddress: 0.0.0.0:10249
---
apiVersion: v1alpha1
kind: KubeFlannelCNIConfig
$patch: delete
---
apiVersion: v1alpha1
kind: KubeAdmissionControlConfig
name: PodSecurity
configuration:
  exemptions:
    namespaces:
      - metallb
      - metallb-config
      - topolvm-system
      - longhorn-system
      - kyverno
      - system-upgrade
      - openebs
      - snapshot-controller
      - volsync
      - flux-system
